package model3;
// Generated 29.Aðu.2019 15:45:48 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Haberler generated by hbm2java
 */
@Entity
@Table(name = "haberler")
public class Haberler implements java.io.Serializable {

	private Integer hid;
	private String hbaslik;
	private String hresim;
	private String hdetay;

	public Haberler() {
	}

	public Haberler(String hbaslik, String hresim, String hdetay) {
		this.hbaslik = hbaslik;
		this.hresim = hresim;
		this.hdetay = hdetay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "hid", unique = true, nullable = false)
	public Integer getHid() {
		return this.hid;
	}

	public void setHid(Integer hid) {
		this.hid = hid;
	}

	@Column(name = "hbaslik", nullable = false)
	public String getHbaslik() {
		return this.hbaslik;
	}

	public void setHbaslik(String hbaslik) {
		this.hbaslik = hbaslik;
	}

	@Column(name = "hresim", nullable = false)
	public String getHresim() {
		return this.hresim;
	}

	public void setHresim(String hresim) {
		this.hresim = hresim;
	}

	@Column(name = "hdetay", nullable = false, length = 65535)
	public String getHdetay() {
		return this.hdetay;
	}

	public void setHdetay(String hdetay) {
		this.hdetay = hdetay;
	}

}
